### ISSUE TITLE
Netflow

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/FCParser#4]
Jose, as far as I can remember, nfcapd functionality is not supported anymore, right? If that is the case, we need to modify INSTALL file accordingly.

**Comment by manjurvaz** [comment]
fcparser makes use of os.system("nfdump -r..."). In case of getting the following error message: "Old common v0 records no longer supported", it is because the data is in v0 record format which is no longer supported by nfdump. In that case, it is necessary to convert the data to new supported version: https://github.com/phaag/nfdump/issues/261
